package com.trucksup.field_officer.presenter.view.activity.truckSupplier.model

data class RcResponse(
    val bodytype: String? = null,
    val carryingcapacity: String,
    val chassisno: String,
    val engineno: String,
    val errorMessage: String,
    val fitnessvalidity: Any,
    val insurancename: String,
    val insurancevalidity: String,
    val isSuccess: Boolean,
    val isbodytypeverify: String,
    val iscarryingcapacityverify: String,
    val ischassisnoverify: String,
    val isenginenoverify: String,
    val isfitnessvalidityverify: String,
    val isinsurancenameverify: String,
    val isinsurancevalidityverify: String,
    val isnationalpermitvalidityverify: String,
    val isownermobileno1verify: String,
    val isownermobileno2verify: Any,
    val isownernameverify: String,
    val ispolicynoverify: String,
    val ispucvalidityverify: String,
    val isregistrationdateverify: String,
    val istypeofsourcingverify: String,
    val isyearvalidityverify: String,
    val nationalpermitvalidity: Any,
    val ownermobileno1: Any,
    val ownermobileno2: Any,
    val ownername: String,
    val policyno: String,
    val pucvalidity: Any,
    val registrationdate: String,
    val typeofsourcing: String,
    val vehicleno: String,
    val vehiclestatus: Any,
    val yearvalidity: Any
)